name: Build and Release SKSE Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      COMMONLIB_SSE_FOLDER: ${{ github.workspace }}/CommonLibSSE-NG
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone CommonLibSSE-NG
        run: git clone --depth 1 https://github.com/CharmedBaryon/CommonLibSSE-NG.git $COMMONLIB_SSE_FOLDER

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
          $VCPKG_ROOT/bootstrap-vcpkg.bat

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
        env:
          COMMONLIB_SSE_FOLDER: ${{ env.COMMONLIB_SSE_FOLDER }}
          VCPKG_ROOT: ${{ env.VCPKG_ROOT }}

      - name: Build SKSE Plugin
        run: cmake --build build --config Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SKSE_Plugin
          path: build/Release/*.dll

      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          files: build/Release/*.dll
          tag_name: latest
          draft: false
          prerelease: false
